.PHONY: build vet test test-ci test-internal compose-up compose-down acceptance

build:
	cd event_processor && go build ./...
	cd notification_service && go build ./...

vet:
	cd event_processor && go vet ./...
	cd notification_service && go vet ./...

test-internal:
	cd event_processor && go test ./internal/...
	cd notification_service && go test ./internal/...

test:
	cd event_processor && go test ./...
	cd notification_service && go test ./...

test-ci:
	cd event_processor && RUN_INTEGRATION=1 go test ./...
	cd notification_service && RUN_INTEGRATION=1 go test ./...

compose-up:
	docker compose up -d --build

compose-down:
	docker compose down

acceptance: build vet test compose-up
